# Generated by Django 4.0.6 on 2022-08-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('no_barang', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('no_sku', models.CharField(max_length=20)),
                ('ukuran', models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43')], max_length=2, null=True)),
                ('jumlah_barang', models.IntegerField(null=True)),
                ('Jenis_barang', models.CharField(max_length=25)),
            ],
        ),
    ]
