# Generated by Django 4.0.6 on 2022-08-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Jenis_barang',
            field=models.CharField(choices=[('Vans', 'Vans'), ('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Hushpuppies', 'Hushpuppies'), ('Kenzo', 'Kenzo'), ('Converse', 'Converse'), ('Reebok', 'Reebok'), ('Reebok', 'Reebok'), ('Jordan', 'Jordan'), ('Stussy', 'Stussy'), ('Volcom', 'Volcom'), ('New Balance', 'New Balance'), ('Thrasher', 'Thrasher'), ('Champion', 'Champion')], max_length=25, null=True),
        ),
    ]
