# Generated by Django 4.0.6 on 2022-08-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_inventory_jenis_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('no_barang', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('no_sku', models.CharField(max_length=20)),
                ('ukuran', models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43')], max_length=2, null=True)),
                ('jumlah_barang', models.IntegerField(null=True)),
                ('Jenis_barang', models.CharField(choices=[('Vans', 'Vans'), ('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Hushpuppies', 'Hushpuppies'), ('Kenzo', 'Kenzo'), ('Converse', 'Converse'), ('Reebok', 'Reebok'), ('Reebok', 'Reebok'), ('Jordan', 'Jordan'), ('Stussy', 'Stussy'), ('Volcom', 'Volcom'), ('New Balance', 'New Balance'), ('Thrasher', 'Thrasher'), ('Champion', 'Champion')], max_length=25, null=True)),
                ('note', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
